/**
 * Air Brawl sound manifest. Every file is generated by `scripts/generate-audio.mjs`
 * (original synthesis — no sampled or third-party audio). Mounted on both the
 * host and the phone via `AudioRuntime`.
 */
import type { SoundManifest } from "@air-jam/sdk";

const sfx = (name: string, volume = 0.6) => ({ src: [`/sounds/${name}.wav`], volume, category: "sfx" as const });

export const AIR_BRAWL_SOUNDS = {
  hitLight: sfx("hit-light", 0.55),
  hitMid: sfx("hit-mid", 0.65),
  hitHeavy: sfx("hit-heavy", 0.8),
  hitMega: sfx("hit-mega", 0.95),
  swing: sfx("swing", 0.3),
  swingHeavy: sfx("swing-heavy", 0.4),
  shield: sfx("shield", 0.55),
  shieldBreak: sfx("shield-break", 0.85),
  jump: sfx("jump", 0.4),
  doubleJump: sfx("double-jump", 0.45),
  land: sfx("land", 0.4),
  dash: sfx("dash", 0.35),
  dodge: sfx("dodge", 0.45),
  grab: sfx("grab", 0.55),
  throw: sfx("throw", 0.6),
  special: sfx("special", 0.55),
  projectile: sfx("projectile", 0.5),
  explosion: sfx("explosion", 0.85),
  teleport: sfx("teleport", 0.5),
  clash: sfx("clash", 0.7),
  ledge: sfx("ledge", 0.4),
  item: sfx("item", 0.6),
  itemSpawn: sfx("item-spawn", 0.45),
  hazardWarn: sfx("hazard-warn", 0.5),
  hazardFire: sfx("hazard-fire", 0.75),
  ko: sfx("ko", 0.95),
  finalKo: sfx("final-ko", 1),
  respawn: sfx("respawn", 0.6),
  countdown: sfx("countdown", 0.7),
  go: sfx("go", 0.85),
  victory: sfx("victory", 0.9),
  crowd: sfx("crowd", 0.5),
  uiMove: sfx("ui-move", 0.4),
  uiSelect: sfx("ui-select", 0.55),
  uiBack: sfx("ui-back", 0.45),
  ready: sfx("ready", 0.6),
  join: sfx("join", 0.6),
  menuMusic: { src: ["/sounds/music-menu.wav"], volume: 0.34, loop: true, category: "music" as const },
  battleMusic: { src: ["/sounds/music-battle.wav"], volume: 0.3, loop: true, category: "music" as const },
} satisfies SoundManifest;

export type AirBrawlSoundId = keyof typeof AIR_BRAWL_SOUNDS;
